### ISSUE TITLE
File extension check doesn't handle spaces properly

### ISSUE THREAD

**Issue by boonebgorges** [lenasterg/bp-group-documents#3]
Hi @lenasterg - Apologies if you're not using this GitHub repo, but I wasn't sure how else to report this issue.

The default format of the `bp_group_documents_valid_file_formats` option has commas followed by spaces: `'doc, docx, gif, gz, jpeg, jpg, ods, odt, pdf, png, pps, ppsx, ppt, pptx, rtf, tar, txt, xls, xlsx, zip'`. But this isn't parsed properly in `bp_group_documents_check_ext()`. The line `explode( ',', $valid_formats_string )` results in an array like this:

```
[
  ' doc',
  ' docx',
  ' gif',
   ...
]
```

Note the spaces at the beginning of these strings. As a result, all uploads are being rejected. A simple fix is to run everything through `trim()`:

```php
	$valid_formats_string = get_option( 'bp_group_documents_valid_file_formats' );
	$valid_formats_array  = explode( ',', $valid_formats_string );
        $valid_formats_array  = array_map( 'trim', $valid_formats_array );
```

**Comment by lenasterg** [comment]
@boonebgorges, thank you so much for spotting the issue and suggesting a solution. 
I added in version 1.22.
